### ISSUE TITLE
timezone broken?

### ISSUE THREAD

**Issue by patrickdrd** [CHEF-KOCH/TBCK#2]
is it possible that some of thunderbird entries broke my timezone?

I'm getting utc date in displayed emails,
while utc+2 is my timezone,
I don't know when it broke,
maybe it is because I applied your user.js entries?

**Comment by CHEF-KOCH** [comment]
Thunderbird normally converts the times stored in eMails to local time.

```
user_pref("general.useragent.locale", "en-US");
user_pref("intl.accept_languages", "en-US, en");
```

Both affecting the time zone if no other timezone was manually set. Make sure you go to Settings > Time & Language. In the left pane, select Date & Time. The date & Time settings here you can set the time to adjust automatically or change it manually.

The reason why it was set to a diff zone is that it prevents possible Date header field leakage.

**Comment by patrickdrd** [comment]
where are those settings?
I can't find them,
all I could find was
tools -> options -> advanced -> general -> date and time formatting and
they are correct there (regional settings locale set correctly),

can I disable date header field leakage?

**Comment by CHEF-KOCH** [comment]
If the 
* OS time is correct
* Thunderbird time + the string for the actual location (language)

... are all correct then it has nothing to do with my configuration, it's server-side time which has a wrong time zone.

**Comment by patrickdrd** [comment]
1) os time is perfectly fine,
2) server side time is fine as well, I checked on my mobile using aquamail
3) it should be your configuration, 99,9%,
because it is the only significant change I made on TB for months, if not years, if not... ages

**Comment by CHEF-KOCH** [comment]
Then don't use it.
