### ISSUE TITLE
Can't see default or any other theme + small fonts

### ISSUE THREAD

**Issue by drkui** [CHEF-KOCH/TBCK#5]
After adding the user.js file, I'm not able to see the default themes or any themes for that matter. Also, text all around looks smaller now.

**Comment by CHEF-KOCH** [comment]
Low effort posts like that are not welcome in any of my repos. First and last warning.

- What TB version?
- What themes?
- What extensions (addons) installed?
- Screenshots?

**Comment by drkui** [comment]
My apologies, I wasn't sure what was needed.

1. 68.5.0 (32-bit). I'm using Mozilla Thunderbird, Portable Edition from PortableApps.com
2. I don't see any themes in the Themes section, there should be the default white theme and a dark theme. I don't see either.
![image](https://user-images.githubusercontent.com/11448650/74582253-7835a580-4f6e-11ea-9b01-25af45076405.png)
3. Here are my installed extensions/addons. Note: Monterail Full Dark is supposed to be a theme, but it's now in Extensions for some reason.
![image](https://user-images.githubusercontent.com/11448650/74582259-91d6ed00-4f6e-11ea-9d70-59166ac53489.png)
![image](https://user-images.githubusercontent.com/11448650/74582269-aca96180-4f6e-11ea-94e0-574210d1608b.png)

As for the smaller text, I'm not sure if I can show it through a screenshot, but here it is:
![image](https://user-images.githubusercontent.com/11448650/74582296-f85c0b00-4f6e-11ea-8746-8bd03aa27ae2.png)

**Comment by CHEF-KOCH** [comment]
Should be fixed with latest uer.js and TB 74 Beta 1.
