### ISSUE TITLE
user-agent header

### ISSUE THREAD

**Issue by fabianski7** [CHEF-KOCH/TBCK#6]
The `user_pref("mailnews.headers.showUserAgent", false) option; ` does not remove the user-agent from the header of emails sent by thunderbird.

You need to create a blank string for `general.useragent.override`.

https://www.ghacks.net/2012/09/08/hide-the-user-agent-when-sending-emails-with-thunderbird/

**Comment by CHEF-KOCH** [comment]
Martins article is from 2012 and incorrect, the correct bug ticket regarding this is [this one](https://bugzilla.mozilla.org/show_bug.cgi?id=223943). 


Can you verify that the bug was closed but false does not work?

**Comment by fabianski7** [comment]
Here are the headers of an email sent without the `general.useragent.override`

```
From me@mail.com Sun Mar 22 02:32:23 2020
To: you@mail.com
From: Me <me@mail.com>
Subject: Bug
Message-ID: <jhjhuyuy-4321-1234-8dec-79251xsd091f@mail.com>
Date: Sat, 21 Mar 2020 23:32:23 -0300
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101
 Firefox/68.0 Thunderbird/68.6.0
MIME-Version: 1.0
Content-Type: multipart/mixed;
 boundary="------------6546546REW4646464654A464"
Content-Language: en-US
```


And after adding it

```
From me@mail.com Sun Mar 22 04:15:27 2020
To: you@mail.com
From: Me <me@mail.com>
Subject: Test
Message-ID: <jhjhuyuy-4321-1234-8dec-79251xsd091f@mail.com>
Date: Sun, 22 Mar 2020 01:15:27 -0300
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Language: en-US
Content-Transfer-Encoding: 7bit
```

**Comment by CHEF-KOCH** [comment]
`general.useragent.override` was not altered because it increases entropy which makes you more fngerprintable and some other clients marking the mail as "spam" if no user agent was detected.

However, as long no one complains I see no reason to not merge it but I will report this in the bug tracker.
