### ISSUE TITLE
mail.server.server#.directory оverwritten

### ISSUE THREAD

**Issue by desperadik** [CHEF-KOCH/TBCK#8]
mail.server.server#.directory оverwritten with default parametrs.

I wanted to change the folder for storing mail through the interface.

Mailbox Settings - Server Settings - Local Directory.

I wanted to connect a folder with mail that is on the network at the address - \\mail_storage\mailbox.at.com

The interface does not accept the selected value.

But if you delete the lines in user.js with `network` the interface already sees the changes and allows them to be saved.

P.S. there was no time to figure out which parameter it was blocking. Thanks.

**Comment by CHEF-KOCH** [comment]
What Thunderbird version + language?

**Comment by CHEF-KOCH** [comment]
Not reproducible & missing information, need to close.
